name: Terraform Apply

on:
  push:
    branches:
      - feature/landing-zone
    paths:
      - 'environment/preprod/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell -ExecutionPolicy Bypass -File {0}
        working-directory: environment/preprod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: '& "C:\Users\kshitij verma\Downloads\terraform_1.15.5_windows_amd64\terraform.exe" init'

      - name: Terraform Validate
        run: '& "C:\Users\kshitij verma\Downloads\terraform_1.15.5_windows_amd64\terraform.exe" validate'

      - name: Terraform Plan
        run: '& "C:\Users\kshitij verma\Downloads\terraform_1.15.5_windows_amd